[[ -n "${DO_DISPLAY:-}" ]] || return 0

info "=== MHS35 + Display dashboard (X11 kiosk) ==="

# Удаляем старый systemd-сервис (мы перешли на autostart)
if [[ -f /etc/systemd/system/travel-nas-display.service ]]; then
    sudo systemctl disable --now travel-nas-display.service 2>/dev/null || true
    sudo rm -f /etc/systemd/system/travel-nas-display.service
    sudo systemctl daemon-reload
fi

if (
    set -e
    fetch_script "travel-nas-display.py"     "$SCRIPT_DIR/travel-nas-display.py"
    fetch_script "backup-progress-writer.py" "$SCRIPT_DIR/backup-progress-writer.py"
    fetch_script "touch-calibrate.sh"        "$SCRIPT_DIR/touch-calibrate.sh"
    fetch_script "screen-rotate.sh"          "$SCRIPT_DIR/screen-rotate.sh"
    fetch_script "fast-shutdown.sh"          "$SCRIPT_DIR/fast-shutdown.sh"
    fetch_script "fast-reboot.sh"            "$SCRIPT_DIR/fast-reboot.sh"

    # systemd-shutdown hook: вызывается в КОНЦЕ shutdown'а (после unit
    # stops, перед halt syscall). Делает lazy umount T7 + SysRq emergency
    # fallback. Pi 5 без него может застрять на 'Reached target system
    # power off' навсегда (USB-bridge T7 блокирует hardware power-down).
    sudo mkdir -p /usr/lib/systemd/system-shutdown/
    fetch_script "zzz-sysrq-fallback" "/usr/lib/systemd/system-shutdown/zzz-sysrq-fallback"
    sudo chmod 755 /usr/lib/systemd/system-shutdown/zzz-sysrq-fallback

    # xinput-calibrator — для touch-calibrate.sh (резистивные сенсоры
    # требуют per-device калибровки чтобы тап попадал в визуальную точку).
    if ! command -v xinput_calibrator >/dev/null 2>&1; then
        wait_for_apt
        apt_install xinput-calibrator
    fi

    # services.conf — список URL для страницы Services. oleg-owned чтобы
    # редактировать без sudo (там нет секретов).
    sudo mkdir -p "$CONFIG_DIR"
    if [[ ! -f "$CONFIG_DIR/services.conf" ]]; then
        fetch_conf_example "services.conf.example" "$CONFIG_DIR/services.conf"
    fi
    sudo chown "$(whoami):$(whoami)" "$CONFIG_DIR/services.conf"
    sudo chmod 0644 "$CONFIG_DIR/services.conf"

    DASHBOARD_USER="$(whoami)"

    # /var/run/travel-nas (tmpfs) — пишут dashboard и udev-скрипты.
    sudo install -d -o "$DASHBOARD_USER" -g "$DASHBOARD_USER" -m 0775 /var/run/travel-nas
    sudo tee /etc/tmpfiles.d/travel-nas.conf >/dev/null << EOF
d /var/run/travel-nas 0775 $DASHBOARD_USER $DASHBOARD_USER -
EOF
    sudo systemd-tmpfiles --create /etc/tmpfiles.d/travel-nas.conf 2>/dev/null || true

    # Sudoers — даём кнопкам dashboard запускать команды без пароля.
    sudo tee /etc/sudoers.d/travel-nas-dashboard >/dev/null << EOF
# Generated by travel-nas-setup. Allows dashboard buttons to run privileged ops.
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/local/bin/nas-backup.sh
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/local/bin/nas-backup-status.py
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/local/bin/daily-summary.sh
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/local/bin/pi-config-backup.sh
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/local/bin/travel-nas-update
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/local/bin/travel-nas-update --full
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/local/bin/power-mode.sh
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/local/bin/set-led.sh
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/local/bin/docker-mgr.sh
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/sbin/comitup-cli
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/bin/nmcli connection down *
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/bin/systemctl reboot, /usr/bin/systemctl poweroff
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/local/bin/fast-shutdown.sh
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/local/bin/fast-reboot.sh
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/bin/systemctl restart comitup
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/bin/systemctl stop nas-backup-runtime
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/bin/systemctl start --no-block nas-verify.service
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/local/bin/thermal-guard.py --restore
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/local/bin/touch-calibrate.sh
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/local/bin/screen-rotate.sh 0
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/local/bin/screen-rotate.sh 90
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/local/bin/screen-rotate.sh 180
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/local/bin/screen-rotate.sh 270
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/local/bin/screen-rotate.sh flip
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/sbin/smartctl
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/bin/smbstatus
$DASHBOARD_USER ALL=(root) NOPASSWD: /usr/bin/dmesg
EOF
    sudo chmod 0440 /etc/sudoers.d/travel-nas-dashboard
    if ! sudo visudo -c -f /etc/sudoers.d/travel-nas-dashboard >/dev/null; then
        sudo rm -f /etc/sudoers.d/travel-nas-dashboard
        echo "ERR: sudoers file invalid, removed"
        exit 1
    fi

    # Autostart .desktop — запустится при логине пользователя в LXDE
    USER_HOME="/home/$DASHBOARD_USER"
    AUTOSTART_DIR="$USER_HOME/.config/autostart"
    mkdir -p "$AUTOSTART_DIR"
    cat > "$AUTOSTART_DIR/travel-nas-display.desktop" << EOF
[Desktop Entry]
Type=Application
Name=Travel-NAS Display
Comment=Dashboard for travel-NAS
Exec=/usr/bin/python3 /usr/local/bin/travel-nas-display.py
X-GNOME-Autostart-enabled=true
StartupNotify=false
Terminal=false
Hidden=false
EOF

    # Отключаем blanking и screensaver — auto-sleep делаем сами через dpms.
    SS_DIR="$USER_HOME/.config/lxsession/LXDE-pi"
    mkdir -p "$SS_DIR"
    AUTOSTART_FILE="$SS_DIR/autostart"
    for cmd in "@xset s off" "@xset s noblank"; do
        if [[ ! -f "$AUTOSTART_FILE" ]] || ! grep -qF "$cmd" "$AUTOSTART_FILE"; then
            echo "$cmd" >> "$AUTOSTART_FILE"
        fi
    done
    # Старая `@xset -dpms` ломает auto-sleep dashboard — удаляем.
    [[ -f "$AUTOSTART_FILE" ]] && sed -i '/^@xset -dpms$/d' "$AUTOSTART_FILE"

    # Конфликт двух polkit-агентов: PiOS Trixie ставит и lxpolkit (LXDE)
    # и polkit-mate-authentication-agent-1 (через mate-polkit deps от чего-то).
    # Оба автостартуют, второй получает DBus error "An authentication agent
    # already exists" → popup на десктопе при логине. Отключаем MATE-агента
    # через user-уровневый XDG-override (Hidden=true).
    POLKIT_OVERRIDE="$AUTOSTART_DIR/polkit-mate-authentication-agent-1.desktop"
    if [[ -f /etc/xdg/autostart/polkit-mate-authentication-agent-1.desktop ]] \
       && [[ ! -f "$POLKIT_OVERRIDE" ]]; then
        cat > "$POLKIT_OVERRIDE" << 'EOF'
[Desktop Entry]
Type=Application
Name=PolicyKit Authentication Agent (disabled by travel-nas-setup)
Comment=Disabled — conflicts with lxpolkit (LXDE has its own agent)
Exec=true
Hidden=true
X-GNOME-Autostart-enabled=false
NoDisplay=true
EOF
    fi

    # PCManFM popup при USB → off (перехватывает фокус с dashboard).
    for PCMANFM_DIR in "$USER_HOME/.config/pcmanfm/LXDE-pi" "$USER_HOME/.config/pcmanfm/default"; do
        mkdir -p "$PCMANFM_DIR"
        PCMANFM_CONF="$PCMANFM_DIR/pcmanfm.conf"
        if [[ ! -f "$PCMANFM_CONF" ]]; then
            cat > "$PCMANFM_CONF" << 'EOF'
[volume]
mount_on_startup=0
mount_removable=0
autorun=0
EOF
        else
            if grep -q '^\[volume\]' "$PCMANFM_CONF"; then
                sed -i '/^\[volume\]/,/^\[/{
                    s/^mount_on_startup=.*/mount_on_startup=0/
                    s/^mount_removable=.*/mount_removable=0/
                    s/^autorun=.*/autorun=0/
                }' "$PCMANFM_CONF"
            else
                printf '\n[volume]\nmount_on_startup=0\nmount_removable=0\nautorun=0\n' \
                    >> "$PCMANFM_CONF"
            fi
        fi
    done
); then
    mark_ok "DISPLAY_DASHBOARD" "autostart + sudoers готовы"
else
    mark_fail "DISPLAY_DASHBOARD" "autostart setup failed"
fi

# Драйвер MHS35 — только если ещё не установлен
if [[ ! -f /etc/X11/xorg.conf.d/40-libinput.conf.bak ]] && [[ ! -d /tmp/LCD-show ]]; then
    warn "Драйвер MHS35 РЕБУТИТ Pi!"
    echo "Запустить установку драйвера MHS35 сейчас? (y/N)"
    read -r ans
    if [[ "$ans" == "y" || "$ans" == "Y" ]]; then
        cd /tmp
        if sudo git clone https://github.com/goodtft/LCD-show.git 2>/dev/null; then
            cd /tmp/LCD-show
            sudo "./MHS35-show" "90"
            # сюда не дойдём — ребут
        else
            mark_fail "DISPLAY_DRIVER" "git clone failed"
        fi
    else
        info "Драйвер MHS35 пропущен (запусти потом: cd /tmp/LCD-show && sudo ./MHS35-show 90)"
    fi
else
    info "Драйвер MHS35 уже установлен"
fi
