[[ -n "${DO_PI_TWEAKS:-}" ]] || return 0

info "=== Pi-specific tweaks (watchdog + EEPROM + sysctl + WiFi) ==="
if (
    set -e
    NEED_REBOOT=0

    # === 1. Hardware watchdog (BCM2712 на Pi 5 / Pi 4) ===========================
    info "→ Hardware watchdog"

    BOOT_CFG="/boot/firmware/config.txt"
    if ! grep -qE "^dtparam=watchdog=on" "$BOOT_CFG"; then
        echo "dtparam=watchdog=on" | sudo tee -a "$BOOT_CFG" >/dev/null
        info "  + dtparam=watchdog=on (нужен reboot чтобы /dev/watchdog появился)"
        NEED_REBOOT=1
    fi

    if ! dpkg -s watchdog &>/dev/null; then
        wait_for_apt
        apt_install watchdog
    fi

    sudo tee /etc/watchdog.conf >/dev/null << 'EOF'
# Generated by travel-nas-setup. BCM2712 hardware watchdog.
# Если ядро hangs (kernel panic, scheduler stall, infinite I/O wait)
# железо само ребутает через watchdog-timeout сек.

watchdog-device = /dev/watchdog
watchdog-timeout = 15

# Если 1-min load avg > этого числа — считаем ядро завесилось → reboot.
# 24 безопасно для Pi 5 (4 ядра × 6 в норме под полной нагрузкой).
max-load-1 = 24

# Watchdog-daemon работает реалтайм — не свопится сам
realtime = yes
priority = 1
EOF

    sudo systemctl enable watchdog
    # restart может не сработать если /dev/watchdog ещё нет (нужен reboot)
    sudo systemctl restart watchdog 2>/dev/null || \
        info "  watchdog.service попробует стартануть после reboot"

    # === 2. EEPROM auto-update (только Pi 5) ====================================
    info "→ EEPROM firmware monthly check"

    if ! command -v rpi-eeprom-update >/dev/null; then
        wait_for_apt
        apt_install rpi-eeprom
    fi

    # Текущий статус — для лога
    sudo rpi-eeprom-update 2>/dev/null | head -3 || true

    write_systemd_unit eeprom-check.service << 'EOF'
[Unit]
Description=Travel-NAS monthly Pi EEPROM check (rpi-eeprom-update -a)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/bin/rpi-eeprom-update -a
EOF

    write_systemd_unit eeprom-check.timer << 'EOF'
[Unit]
Description=Run EEPROM check monthly

[Timer]
OnCalendar=monthly
Persistent=true
Unit=eeprom-check.service

[Install]
WantedBy=timers.target
EOF
    sudo systemctl daemon-reload
    sudo systemctl enable --now eeprom-check.timer

    # === 3. WiFi powersave off + sysctl ========================================
    info "→ WiFi powersave OFF + sysctl tunes"

    sudo tee /etc/sysctl.d/99-travel-nas-tunes.conf >/dev/null << 'EOF'
# Generated by travel-nas-setup. SSD/NAS-friendly tunes.

# Меньше свопить — мы на ext4 SSD, swap = wear на microSD
vm.swappiness = 10

# Больше TCP-connections под Samba/Photoview когда заходишь с нескольких
# устройств (default 4096, но backlog 128 мало для concurrent multi-client)
net.core.somaxconn = 512

# Keepalive короче — быстрее детектим оборванные TCP (хороший WiFi)
net.ipv4.tcp_keepalive_time = 120
net.ipv4.tcp_keepalive_intvl = 30
net.ipv4.tcp_keepalive_probes = 3
EOF
    sudo sysctl -p /etc/sysctl.d/99-travel-nas-tunes.conf >/dev/null

    # WiFi powersave OFF для всех сохранённых wifi-соединений
    # NM-вариант persistent (выдержит реконнект, не перезатрётся).
    # 2 = disable, 3 = enable, 0 = default (= enable на Pi)
    WIFI_PATCHED=0
    while IFS= read -r conn; do
        [[ -z "$conn" ]] && continue
        if sudo nmcli connection modify "$conn" 802-11-wireless.powersave 2 2>/dev/null; then
            WIFI_PATCHED=$((WIFI_PATCHED + 1))
        fi
    done < <(nmcli -t -f NAME,TYPE c show 2>/dev/null | awk -F: '$2=="802-11-wireless"{print $1}')

    # Применяем сейчас на активный интерфейс (не ждать реконнекта)
    sudo iw dev wlan0 set power_save off 2>/dev/null || true

    info "  WiFi powersave OFF на $WIFI_PATCHED connection'ах"

); then
    if [[ "${NEED_REBOOT:-0}" -eq 1 ]]; then
        mark_ok "PI_TWEAKS" "watchdog + EEPROM + sysctl + WiFi — нужен reboot"
    else
        mark_ok "PI_TWEAKS" "watchdog + EEPROM + sysctl + WiFi"
    fi
else
    mark_fail "PI_TWEAKS" "tweaks setup failed"
fi
