[[ -n "${DO_DESKTOP_AUTH:-}" ]] || return 0

info "=== Passwordless polkit (меньше запросов пароля) ==="
# Личный travel-NAS с физическим доступом владельца: члены группы sudo (юзер
# uid 1000) проходят polkit БЕЗ запроса пароля — настройки/монтирование/сеть/
# обновления в десктопе больше не нагло спрашивают пароль каждый раз.
# Терминальный sudo это НЕ трогает (там своя политика + наш NOPASSWD-список).
# Это ОСЛАБЛЕНИЕ безопасности — поэтому компонент opt-in (по умолчанию выключен
# в меню, не входит в --all). Убрать обратно = удалить .rules-файл.
RULE_FILE=/etc/polkit-1/rules.d/49-travel-nas-nopasswd.rules

if [[ ! -d /etc/polkit-1/rules.d ]]; then
    mark_fail "DESKTOP_AUTH" "нет /etc/polkit-1/rules.d (polkit без JS-rules?)"
    return 0
fi

if sudo tee "$RULE_FILE" >/dev/null << 'RULE'
// Generated by travel-nas-setup (компонент DESKTOP_AUTH, opt-in).
// Члены группы sudo проходят polkit без запроса пароля на этом личном
// устройстве. Терминальный sudo не затрагивается. Убрать = удалить файл.
polkit.addRule(function(action, subject) {
    if (subject.isInGroup("sudo")) {
        return polkit.Result.YES;
    }
});
RULE
then
    sudo chmod 0644 "$RULE_FILE"
    sudo systemctl restart polkit 2>/dev/null || true
    mark_ok "DESKTOP_AUTH" "polkit: группа sudo без пароля"
else
    mark_fail "DESKTOP_AUTH" "не удалось записать $RULE_FILE"
fi
