[[ -n "${DO_DESKTOP_AUTH:-}" ]] || return 0

info "=== Passwordless polkit + reboot/poweroff (меньше запросов пароля) ==="
# Личный travel-NAS с физическим доступом владельца. Делаем две вещи для группы
# sudo (юзер uid 1000):
#   1) polkit — GUI-действия (настройки/монтирование/сеть/обновления) без пароля;
#   2) sudoers — reboot/poweroff/shutdown в ТЕРМИНАЛЕ без пароля (polkit на это
#      не влияет — у sudo своя политика).
# Это ОСЛАБЛЕНИЕ безопасности → компонент opt-in (по умолчанию выкл в меню, не
# входит в --all). Откат: удалить оба файла (см. пути ниже).
RULE_FILE=/etc/polkit-1/rules.d/49-travel-nas-nopasswd.rules
SUDO_FILE=/etc/sudoers.d/travel-nas-poweroff
OK_POLKIT=0; OK_SUDO=0

# --- 1) polkit: группа sudo проходит все действия без пароля ------------------
if [[ -d /etc/polkit-1/rules.d ]]; then
    if sudo tee "$RULE_FILE" >/dev/null << 'RULE'
// Generated by travel-nas-setup (компонент DESKTOP_AUTH, opt-in).
// Члены группы sudo проходят polkit без запроса пароля на этом личном
// устройстве. Терминальный sudo не затрагивается. Убрать = удалить файл.
polkit.addRule(function(action, subject) {
    if (subject.isInGroup("sudo")) {
        return polkit.Result.YES;
    }
});
RULE
    then
        sudo chmod 0644 "$RULE_FILE"
        sudo systemctl restart polkit 2>/dev/null || true
        OK_POLKIT=1
    fi
else
    warn "нет /etc/polkit-1/rules.d — polkit-часть пропущена (polkit без JS-rules?)"
fi

# --- 2) sudoers: reboot/poweroff/shutdown в терминале без пароля ---------------
# Пути и /usr/sbin, и /sbin (на merged-usr это симлинки, но sudo матчит по
# вызванному пути) + systemctl-варианты. Валидируем visudo'ом перед применением —
# битый sudoers-файл может лишить sudo вообще.
if sudo tee "$SUDO_FILE" >/dev/null << 'SUDOERS'
# Generated by travel-nas-setup (DESKTOP_AUTH, opt-in). Passwordless питание
# в терминале для группы sudo. GUI-ребут уже без пароля через polkit.
%sudo ALL=(root) NOPASSWD: /usr/sbin/reboot, /sbin/reboot, /usr/sbin/poweroff, /sbin/poweroff, /usr/sbin/halt, /sbin/halt, /usr/sbin/shutdown, /sbin/shutdown, /usr/bin/systemctl reboot, /usr/bin/systemctl poweroff
SUDOERS
then
    sudo chmod 0440 "$SUDO_FILE"
    if sudo visudo -c -f "$SUDO_FILE" >/dev/null 2>&1; then
        OK_SUDO=1
    else
        sudo rm -f "$SUDO_FILE"
        warn "sudoers $SUDO_FILE невалиден — удалил (sudo не сломан)"
    fi
fi

if [[ $OK_POLKIT -eq 1 || $OK_SUDO -eq 1 ]]; then
    mark_ok "DESKTOP_AUTH" "polkit=$OK_POLKIT, sudo reboot/poweroff=$OK_SUDO"
else
    mark_fail "DESKTOP_AUTH" "ни polkit, ни sudoers не применились"
fi
