[[ -n "${DO_WEBDASH:-}" ]] || return 0

info "=== Web dashboard (DSI, Flask + Chromium kiosk) ==="

# Веб-дашборд под DSI 800×480. Старый pygame-дашборд — для MHS35, его не трогаем.
# Имеет смысл только на DSI (на MHS35 320×480 не влезет и не нужен).
WD_DIR=/opt/travel-nas-dashboard
WD_PORT=8090
DASH_USER="$(getent passwd 1000 | cut -d: -f1)"; DASH_USER="${DASH_USER:-$(whoami)}"
USER_HOME="/home/$DASH_USER"

if (
    set -e

    # 1) Flask (apt, не pip — на Trixie PEP668 ломает системный pip)
    if ! python3 -c "import flask" 2>/dev/null; then
        wait_for_apt; apt_install python3-flask
    fi

    # 2) Код + статика
    sudo mkdir -p "$WD_DIR/static"
    fetch_script "webdash/server.py"          "$WD_DIR/server.py"
    fetch_script "webdash/static/index.html"  "$WD_DIR/static/index.html"
    fetch_script "webdash/static/app.js"      "$WD_DIR/static/app.js"
    fetch_script "webdash/static/style.css"   "$WD_DIR/static/style.css"

    # uPlot (вендорим локально — дашборд должен работать оффлайн)
    UP=1.6.31
    if [[ ! -s "$WD_DIR/static/uplot.min.js" ]]; then
        sudo curl -fsSL "https://cdn.jsdelivr.net/npm/uplot@$UP/dist/uPlot.iife.min.js" -o "$WD_DIR/static/uplot.min.js"
        sudo curl -fsSL "https://cdn.jsdelivr.net/npm/uplot@$UP/dist/uPlot.min.css" -o "$WD_DIR/static/uplot.min.css"
    fi

    # 3) Конфиг + папка истории на /mnt/storage (не на microSD)
    sudo mkdir -p "$CONFIG_DIR"
    [[ -f "$CONFIG_DIR/webdash.conf" ]] || fetch_conf_example "webdash.conf.example" "$CONFIG_DIR/webdash.conf"
    sudo chmod 0644 "$CONFIG_DIR/webdash.conf"
    sudo install -d -o "$DASH_USER" -g "$DASH_USER" "$STORAGE_MOUNT/.travel-nas" 2>/dev/null || true

    # 4) sudoers — действия дашборда без пароля (бежит от юзера)
    sudo tee /etc/sudoers.d/travel-nas-webdash >/dev/null << EOF
# Generated by travel-nas-setup (WEBDASH). Действия веб-дашборда.
$DASH_USER ALL=(root) NOPASSWD: /usr/sbin/reboot, /usr/sbin/poweroff
$DASH_USER ALL=(root) NOPASSWD: /usr/local/bin/travel-nas-update
$DASH_USER ALL=(root) NOPASSWD: /usr/local/bin/nas-backup.sh
$DASH_USER ALL=(root) NOPASSWD: /usr/bin/systemctl stop nas-backup-runtime
$DASH_USER ALL=(root) NOPASSWD: /usr/local/bin/cpu-boost.sh on, /usr/local/bin/cpu-boost.sh off
$DASH_USER ALL=(root) NOPASSWD: /usr/local/bin/power-mode.sh auto, /usr/local/bin/power-mode.sh normal, /usr/local/bin/power-mode.sh saver
$DASH_USER ALL=(root) NOPASSWD: /usr/local/bin/dsi-rotate.sh 0, /usr/local/bin/dsi-rotate.sh 90, /usr/local/bin/dsi-rotate.sh 180, /usr/local/bin/dsi-rotate.sh 270
$DASH_USER ALL=(root) NOPASSWD: /usr/sbin/comitup-cli d
$DASH_USER ALL=(root) NOPASSWD: /usr/sbin/smartctl
EOF
    sudo chmod 0440 /etc/sudoers.d/travel-nas-webdash
    if ! sudo visudo -c -f /etc/sudoers.d/travel-nas-webdash >/dev/null; then
        sudo rm -f /etc/sudoers.d/travel-nas-webdash; echo "ERR: webdash sudoers invalid"; exit 1
    fi

    # 5) systemd-сервис (бежит от юзера, после монтирования диска)
    write_systemd_unit travel-nas-webdash.service << EOF
[Unit]
Description=Travel-NAS web dashboard
After=network.target
RequiresMountsFor=$STORAGE_MOUNT

[Service]
User=$DASH_USER
ExecStart=/usr/bin/python3 $WD_DIR/server.py
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF
    sudo systemctl daemon-reload
    sudo systemctl enable --now travel-nas-webdash.service

    # 6) Chromium kiosk — автозапуск в labwc + ярлык на десктоп
    CHROME=$(command -v chromium-browser || command -v chromium || echo chromium-browser)
    KIOSK="$CHROME --kiosk --app=http://localhost:$WD_PORT --ozone-platform=wayland --noerrdialogs --disable-infobars --password-store=basic --disable-features=Translate,TranslateUI --lang=ru-RU --check-for-update-interval=31536000"
    LABWC_AUTO="$USER_HOME/.config/labwc/autostart"
    mkdir -p "$(dirname "$LABWC_AUTO")"
    touch "$LABWC_AUTO"
    grep -q "travel-nas-webdash-kiosk" "$LABWC_AUTO" 2>/dev/null || \
        echo "# travel-nas-webdash-kiosk" >> "$LABWC_AUTO"
    grep -q -- "--app=http://localhost:$WD_PORT" "$LABWC_AUTO" 2>/dev/null || \
        echo "$KIOSK &" >> "$LABWC_AUTO"

    DESK="$USER_HOME/Desktop"; mkdir -p "$DESK"
    cat > "$DESK/Dashboard.desktop" << EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Dashboard
Comment=Travel-NAS dashboard (kiosk)
Exec=$KIOSK
Icon=utilities-system-monitor
Terminal=false
Categories=System;
EOF
    chmod +x "$DESK/Dashboard.desktop"
    command -v gio >/dev/null && gio set "$DESK/Dashboard.desktop" metadata::trusted true 2>/dev/null || true
); then
    mark_ok "WEBDASH" "http://localhost:$WD_PORT (kiosk autostart + сервис)"
else
    mark_fail "WEBDASH" "установка веб-дашборда не удалась"
fi
