[[ -n "${DO_WEBDASH:-}" ]] || return 0

# Только для DSI: на MHS35 — pygame-дашборд, веб тут не нужен и kiosk-автозапуск
# мешал бы. Определяем экран как остальные модули (config.txt → display.conf).
WD_BOOT_CFG=/boot/firmware/config.txt; [[ -f "$WD_BOOT_CFG" ]] || WD_BOOT_CFG=/boot/config.txt
if grep -qE '^[[:space:]]*dtoverlay=vc4-kms-dsi' "$WD_BOOT_CFG" 2>/dev/null; then
    :
elif [[ -f "$CONFIG_DIR/display.conf" ]] && grep -q 'SCREEN_TYPE=dsi43' "$CONFIG_DIR/display.conf" 2>/dev/null; then
    :
else
    info "WEBDASH: пропуск — веб-дашборд ставится только для Waveshare DSI-экрана."
    return 0
fi

info "=== Web dashboard (DSI, Flask + Chromium kiosk) ==="

# Веб-дашборд под DSI 800×480. Старый pygame-дашборд — для MHS35, его не трогаем.
# Имеет смысл только на DSI (на MHS35 320×480 не влезет и не нужен).
WD_DIR=/opt/travel-nas-dashboard
WD_PORT=8090
DASH_USER="$(getent passwd 1000 | cut -d: -f1)"; DASH_USER="${DASH_USER:-$(whoami)}"
USER_HOME="/home/$DASH_USER"

if (
    set -e

    # 1) Flask (apt, не pip — на Trixie PEP668 ломает системный pip)
    if ! python3 -c "import flask" 2>/dev/null; then
        wait_for_apt; apt_install python3-flask
    fi
    # grim — скриншот Wayland для кнопки «Screenshot → Telegram»
    command -v grim >/dev/null 2>&1 || { wait_for_apt; apt_install grim; }

    # 2) Код + статика
    sudo mkdir -p "$WD_DIR/static"
    fetch_script "webdash/server.py"          "$WD_DIR/server.py"
    fetch_script "webdash/static/index.html"  "$WD_DIR/static/index.html"
    fetch_script "webdash/static/app.js"      "$WD_DIR/static/app.js"
    fetch_script "webdash/static/style.css"   "$WD_DIR/static/style.css"
    # cpu-boost.sh — нужен кнопкам CPU Boost. На DSI 19-display его НЕ кладёт
    # (фетч в MHS35-ветке после DSI-return), поэтому кладём здесь сами.
    fetch_script "cpu-boost.sh" /usr/local/bin/cpu-boost.sh

    # uPlot (вендорим локально — дашборд должен работать оффлайн)
    UP=1.6.31
    if [[ ! -s "$WD_DIR/static/uplot.min.js" ]]; then
        sudo curl -fsSL "https://cdn.jsdelivr.net/npm/uplot@$UP/dist/uPlot.iife.min.js" -o "$WD_DIR/static/uplot.min.js"
        sudo curl -fsSL "https://cdn.jsdelivr.net/npm/uplot@$UP/dist/uPlot.min.css" -o "$WD_DIR/static/uplot.min.css"
    fi
    [[ -s "$WD_DIR/static/qrcode.min.js" ]] || \
        sudo curl -fsSL "https://cdn.jsdelivr.net/npm/qrcode-generator@1.4.4/qrcode.js" -o "$WD_DIR/static/qrcode.min.js"

    # 3) Конфиг + папка истории на /mnt/storage (не на microSD)
    sudo mkdir -p "$CONFIG_DIR"
    [[ -f "$CONFIG_DIR/webdash.conf" ]] || fetch_conf_example "webdash.conf.example" "$CONFIG_DIR/webdash.conf"
    sudo chmod 0644 "$CONFIG_DIR/webdash.conf"
    # services.conf — список веб-UI (на DSI 19-display его не создаёт: тот блок
    # для pygame-дашборда). Нужен дашборду (страница Services).
    if [[ ! -f "$CONFIG_DIR/services.conf" ]]; then
        fetch_conf_example "services.conf.example" "$CONFIG_DIR/services.conf"
        sudo chown "$DASH_USER:$DASH_USER" "$CONFIG_DIR/services.conf"; sudo chmod 0644 "$CONFIG_DIR/services.conf"
    fi
    sudo install -d -o "$DASH_USER" -g "$DASH_USER" "$STORAGE_MOUNT/.travel-nas" 2>/dev/null || true

    # 4) sudoers — действия дашборда без пароля (бежит от юзера)
    sudo tee /etc/sudoers.d/travel-nas-webdash >/dev/null << EOF
# Generated by travel-nas-setup (WEBDASH). Действия веб-дашборда.
$DASH_USER ALL=(root) NOPASSWD: /usr/sbin/reboot, /usr/sbin/poweroff
$DASH_USER ALL=(root) NOPASSWD: /usr/local/bin/travel-nas-update
$DASH_USER ALL=(root) NOPASSWD: /usr/local/bin/nas-backup.sh --run, /usr/local/bin/nas-backup.sh --dry-run, /usr/local/bin/nas-backup.sh --diff
$DASH_USER ALL=(root) NOPASSWD: /usr/bin/systemctl stop nas-backup-runtime
$DASH_USER ALL=(root) NOPASSWD: /usr/local/bin/nas-schedule.sh set *, /usr/local/bin/nas-schedule.sh off, /usr/local/bin/nas-schedule.sh toggle
$DASH_USER ALL=(root) NOPASSWD: /usr/local/bin/pi-config-backup.sh
$DASH_USER ALL=(root) NOPASSWD: /usr/local/bin/cpu-boost.sh on, /usr/local/bin/cpu-boost.sh on *, /usr/local/bin/cpu-boost.sh off
$DASH_USER ALL=(root) NOPASSWD: /usr/local/bin/power-mode.sh auto, /usr/local/bin/power-mode.sh normal, /usr/local/bin/power-mode.sh saver
$DASH_USER ALL=(root) NOPASSWD: /usr/local/bin/dsi-rotate.sh 0, /usr/local/bin/dsi-rotate.sh 90, /usr/local/bin/dsi-rotate.sh 180, /usr/local/bin/dsi-rotate.sh 270
$DASH_USER ALL=(root) NOPASSWD: /usr/sbin/comitup-cli d
$DASH_USER ALL=(root) NOPASSWD: /usr/bin/tailscale up, /usr/bin/tailscale down
$DASH_USER ALL=(root) NOPASSWD: /usr/bin/nmcli device reconnect wlan0
$DASH_USER ALL=(root) NOPASSWD: /usr/bin/nmcli device wifi connect *
$DASH_USER ALL=(root) NOPASSWD: /usr/bin/systemctl restart *.service
$DASH_USER ALL=(root) NOPASSWD: /usr/bin/systemctl start --no-block nas-verify.service
$DASH_USER ALL=(root) NOPASSWD: /usr/bin/systemctl restart tg-listener.service
$DASH_USER ALL=(root) NOPASSWD: /usr/bin/systemctl --no-block restart travel-nas-webdash.service
$DASH_USER ALL=(root) NOPASSWD: /usr/bin/tee /etc/travel-nas/*.conf
$DASH_USER ALL=(root) NOPASSWD: /usr/sbin/smartctl
EOF
    sudo chmod 0440 /etc/sudoers.d/travel-nas-webdash
    if ! sudo visudo -c -f /etc/sudoers.d/travel-nas-webdash >/dev/null; then
        sudo rm -f /etc/sudoers.d/travel-nas-webdash; echo "ERR: webdash sudoers invalid"; exit 1
    fi

    # 5) systemd-сервис (бежит от юзера, после монтирования диска)
    write_systemd_unit travel-nas-webdash.service << EOF
[Unit]
Description=Travel-NAS web dashboard
After=network.target
RequiresMountsFor=$STORAGE_MOUNT

[Service]
User=$DASH_USER
ExecStart=/usr/bin/python3 $WD_DIR/server.py
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF
    sudo systemctl daemon-reload
    sudo systemctl enable --now travel-nas-webdash.service

    # 6) Chromium kiosk — автозапуск в labwc + ярлык на десктоп
    CHROME=$(command -v chromium-browser || command -v chromium || echo chromium-browser)
    KIOSK="$CHROME --kiosk --app=http://localhost:$WD_PORT --ozone-platform=wayland --noerrdialogs --disable-infobars --password-store=basic --disable-features=Translate,TranslateUI --lang=ru-RU --check-for-update-interval=31536000"
    LABWC_AUTO="$USER_HOME/.config/labwc/autostart"
    mkdir -p "$(dirname "$LABWC_AUTO")"
    touch "$LABWC_AUTO"
    # ВСЕГДА перезаписываем строку kiosk (а не «добавить если нет») — иначе при
    # смене флагов на устройстве остаётся старая команда. Критично: без
    # --password-store=basic Chromium на буте лезет в gnome-keyring → запрос
    # пароля → серый экран (keyring заблокирован при автологине).
    sed -i '/travel-nas-webdash-kiosk/d' "$LABWC_AUTO"
    sed -i "\#chromium.*--app=http://localhost:$WD_PORT#d" "$LABWC_AUTO"
    printf '# travel-nas-webdash-kiosk\n%s &\n' "$KIOSK" >> "$LABWC_AUTO"

    DESK="$USER_HOME/Desktop"; mkdir -p "$DESK"
    cat > "$DESK/Dashboard.desktop" << EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Dashboard
Comment=Travel-NAS dashboard (kiosk)
Exec=$KIOSK
Icon=utilities-system-monitor
Terminal=false
Categories=System;
EOF
    chmod +x "$DESK/Dashboard.desktop"
    command -v gio >/dev/null && gio set "$DESK/Dashboard.desktop" metadata::trusted true 2>/dev/null || true
); then
    mark_ok "WEBDASH" "http://localhost:$WD_PORT (kiosk autostart + сервис)"
else
    mark_fail "WEBDASH" "установка веб-дашборда не удалась"
fi
