#!/bin/bash
# =============================================================================
# dsi-rotate.sh — поворот Waveshare 4.3″ DSI (дисплей + тач синхронно).
# Только для DSI-экрана. Старый MHS35 поворачивается отдельным screen-rotate.sh
# (другой механизм: dtoverlay:rotate + ADS7846-калибровка) — НЕ путать.
#
# Механизм DSI (метод «lite/CLI» из вики Waveshare):
#   дисплей — cmdline.txt: video=DSI-1:800x480M@60[,rotate=N]
#   тач     — udev LIBINPUT_CALIBRATION_MATRIX (Goodix capacitive)
# Требует reboot — оба применяются на загрузке.
#
# Использование:
#   sudo dsi-rotate.sh 0     нативный ландшафт 800×480 (DSI-разъём по умолчанию)
#   sudo dsi-rotate.sh 90
#   sudo dsi-rotate.sh 180
#   sudo dsi-rotate.sh 270
# =============================================================================
set -e

ROT="${1:-}"
case "$ROT" in
    0|90|180|270) ;;
    *) echo "Usage: $0 {0|90|180|270}" >&2; exit 2 ;;
esac

[[ "$EUID" -eq 0 ]] || exec sudo -- "$0" "$@"

CMDLINE=/boot/firmware/cmdline.txt
[[ -f "$CMDLINE" ]] || CMDLINE=/boot/cmdline.txt
TOUCH_RULE=/etc/udev/rules.d/99-waveshare-touch.rules
CONN=DSI-1
MODE="800x480M@60"

# ── 1) дисплей: одна строка cmdline.txt, заменяем/добавляем токен video=DSI-1 ──
line=$(tr -d '\n' < "$CMDLINE")
line=$(echo "$line" | sed -E "s/[[:space:]]*video=${CONN}:[^[:space:]]*//g")   # выкинуть старый
if [[ "$ROT" == "0" ]]; then
    tok="video=${CONN}:${MODE}"
else
    tok="video=${CONN}:${MODE},rotate=${ROT}"
fi
line=$(echo "${tok} ${line}" | tr -s ' ' | sed 's/^ //; s/ $//')
echo "$line" > "$CMDLINE"
echo "✓ $CMDLINE: $tok"

# ── 2) тач: матрица libinput под угол (0° = identity → правило убираем) ───────
case "$ROT" in
    0)   MATRIX="" ;;
    90)  MATRIX="0 -1 1 1 0 0" ;;
    180) MATRIX="-1 0 1 0 -1 1" ;;
    270) MATRIX="0 1 0 -1 0 1" ;;
esac
if [[ -z "$MATRIX" ]]; then
    rm -f "$TOUCH_RULE"
    echo "✓ touch: identity (правило $TOUCH_RULE удалено)"
else
    cat > "$TOUCH_RULE" << EOF
# Generated by travel-nas-setup — DSI touch rotation $ROT°
ENV{ID_INPUT_TOUCHSCREEN}=="1", ENV{LIBINPUT_CALIBRATION_MATRIX}="$MATRIX"
EOF
    echo "✓ $TOUCH_RULE: rotate=$ROT (matrix \"$MATRIX\")"
fi
udevadm control --reload-rules 2>/dev/null || true

echo
echo "Готово. Для применения нужен reboot:  sudo reboot"
