#!/bin/bash
# =============================================================================
# screen-rotate.sh — повернуть MHS35 (goodtft) экран на 0/90/180/270°
# =============================================================================
# Что меняется:
#   1. /boot/firmware/config.txt → dtoverlay=mhs35,rotate=<deg>
#      (framebuffer ориентация — применяется при загрузке)
#   2. /etc/X11/xorg.conf.d/99-mhs35-touch.conf → TransformationMatrix
#      (тач координаты транспонируются под новый поворот)
#
# Обязательно: reboot после применения.
#
# Использование:
#   screen-rotate.sh             — показать текущий поворот
#   screen-rotate.sh 0           — landscape (480×320)
#   screen-rotate.sh 90          — portrait (320×480) — наш default
#   screen-rotate.sh 180         — landscape, вверх ногами
#   screen-rotate.sh 270         — portrait, вверх ногами
# =============================================================================

set -u

# Self-elevate (для tg-listener / desktop вызовов без sudo)
if [[ "$EUID" -ne 0 ]]; then
    if [[ -t 0 ]]; then
        exec sudo -- "$0" "$@"
    fi
    echo "ERROR: must run as root" >&2
    exit 1
fi

CONFIG=/boot/firmware/config.txt
[[ -f "$CONFIG" ]] || CONFIG=/boot/config.txt
if [[ ! -f "$CONFIG" ]]; then
    echo "ERROR: config.txt не найден ни в /boot/firmware ни в /boot" >&2
    exit 1
fi

ROT="${1:-}"

if [[ -z "$ROT" ]]; then
    CUR=$(grep -oE "dtoverlay=mhs35[^[:space:]]*" "$CONFIG" | head -1)
    DEG=$(echo "$CUR" | grep -oE "rotate=[0-9]+" | cut -d= -f2)
    echo "Current rotation: ${DEG:-90 (default)}"
    echo "Config line: ${CUR:-(no mhs35 overlay)}"
    echo ""
    echo "Usage: $0 [0|90|180|270]"
    echo ""
    echo "  0   = landscape (480×320), кнопки справа"
    echo "  90  = portrait (320×480), кнопки внизу — default"
    echo "  180 = landscape, вверх ногами"
    echo "  270 = portrait, вверх ногами"
    echo ""
    echo "После смены ОБЯЗАТЕЛЕН ребут: sudo reboot"
    exit 0
fi

case "$ROT" in
    0|90|180|270) ;;
    *) echo "Invalid: $ROT (0|90|180|270 only)" >&2; exit 1 ;;
esac

if ! grep -qE "dtoverlay=mhs35" "$CONFIG"; then
    echo "ERROR: нет 'dtoverlay=mhs35' в $CONFIG" >&2
    echo "Драйвер MHS35 не установлен. Сначала прогони LCD-show:" >&2
    echo "  cd /tmp/LCD-show && sudo ./MHS35-show $ROT" >&2
    exit 1
fi

# 1. config.txt — заменяем dtoverlay строку целиком.
# LCD-show может писать через ',' или ':' — матчим оба варианта.
sed -i -E "s|dtoverlay=mhs35[:,][^[:space:]]*|dtoverlay=mhs35,rotate=$ROT|" "$CONFIG"
# Если параметра поворота вообще не было (просто 'dtoverlay=mhs35') — добавляем
sed -i -E "s|dtoverlay=mhs35$|dtoverlay=mhs35,rotate=$ROT|" "$CONFIG"
echo "✓ $CONFIG: dtoverlay=mhs35,rotate=$ROT"

# 2. Touch transformation matrix. Эти 3x3 матрицы — стандартные для xinput
# Coordinate Transformation Matrix.
case "$ROT" in
    0)   MATRIX="1 0 0 0 1 0 0 0 1"        ;;  # identity (landscape native)
    90)  MATRIX="0 -1 1 1 0 0 0 0 1"       ;;  # rotate clockwise 90
    180) MATRIX="-1 0 1 0 -1 1 0 0 1"      ;;  # upside down
    270) MATRIX="0 1 0 -1 0 1 0 0 1"       ;;  # rotate counter-clockwise 90
esac

TOUCH_CONF=/etc/X11/xorg.conf.d/99-mhs35-touch.conf
cat > "$TOUCH_CONF" << EOF
# Generated by screen-rotate.sh — не править вручную
# Поворот: $ROT° → матрица трансформации тач-координат
Section "InputClass"
    Identifier "ADS7846 Touchscreen"
    MatchProduct "ADS7846 Touchscreen"
    Option "TransformationMatrix" "$MATRIX"
EndSection
EOF
echo "✓ $TOUCH_CONF (rotate=$ROT, matrix='$MATRIX')"

# Сохраняем текущий выбор для возможного отката
echo "$ROT" > /var/lib/travel-nas/screen-rotation.txt 2>/dev/null

echo ""
echo "════════════════════════════════════"
echo "  Готово. Применить: sudo reboot"
echo "════════════════════════════════════"
